apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${NAMESPACE}--backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    github.ref: refs/heads/main
    github.sha: 3cceae51bd4d832af4f75e9e62acadf12db1e7e7
    github.action: git-push-service
spec:
  project: monorepo-deploy-actions-demo
  source:
    repoURL: https://github.com/quipper/monorepo-deploy-actions-demo.git
    targetRevision: prebuilt/monorepo-deploy-actions-demo/pr/refs/heads/main
    path: services/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: ${NAMESPACE}
  syncPolicy:
    automated:
      prune: true
