apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development--backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    github.ref: refs/heads/main
    github.sha: 296d5c24b6d823433349b55e93f7ae2b1066ea80
    github.action: git-push-service
spec:
  project: monorepo-deploy-actions-demo
  source:
    repoURL: https://github.com/quipper/monorepo-deploy-actions-demo.git
    targetRevision: ns/monorepo-deploy-actions-demo/development/development
    path: services/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
