apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-1--frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    github.action: git-push-services-from-prebuilt
spec:
  project: monorepo-deploy-actions-demo
  source:
    repoURL: https://github.com/oughtinc/monorepo-deploy-actions-demo.git
    targetRevision: ns/monorepo-deploy-actions-demo/pr/pr-1
    path: services/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: pr-1
  syncPolicy:
    automated:
      prune: true
