apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-19--backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    github.ref: refs/pull/19/merge
    github.sha: b56875a05c4533939197971f01bb71d905bc11a1
    github.action: git-push-services-from-prebuilt
spec:
  project: monorepo-deploy-actions-demo
  source:
    repoURL: https://github.com/quipper/monorepo-deploy-actions-demo.git
    targetRevision: ns/monorepo-deploy-actions-demo/pr/pr-19
    path: services/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: pr-19
  syncPolicy:
    automated:
      prune: true
