apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-9/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:e68cb1f0874c005e358b19c955cc817ef5f9a64582c7d75b7ae5845807bf7db0
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
