apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-16/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-16
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:64271ef18e927b8c21829da652733d19f775f90c7be61459807d23f1ae89205b
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
