apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:3267e04b90a8cd6cd2a09240e948d47b8ffa6780a22af740fddaec2df6314d36
