apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-13/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-13
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:9234b92da4a3fa30cda6a40e00ac207f192936280a1c4feb6474c26b1deaee87
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
