apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-1/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/oughtinc/monorepo-deploy-actions-demo/backend@sha256:f4cbc71b2891d9f1ce95214efbb7eedb9bf15ab7c59038c6c63376d66eb4de01
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
