apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-12/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:c87b2e968fa731253b7fd1025cbfb6509f1aab02cf7b59ff7d4b532205ab5548
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
