apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-7/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-7
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:dad73b30e0aa3759bb2c7bbdb77c65aec9cf8ea3ab21b29a8aa47f24152540fd
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
