apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-development/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:9d57c5f2a4ef05c4f7a744d6ba6bf7ba45ec2dbad701408c29801996e072a81b
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
