apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-17/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-17
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ${DOCKER_IMAGE}
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
