apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:c1b83af487f5f2469aaf38541d86c2356c8b48760686925e2cf94fa43b0784d3
