apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-11/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:b798f2bfbb7864a6a1e000503ee1cf80d1ae518290784a84c8b7fefd0084a17c
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
