apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:7206e08e93622249753444ed62588d624d04cff511e9e213e38268bb2943b76f
