apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-21/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-21
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:8058f705e1920458762a64bdb580070db07e7526cc6c24cc04a5d1d2b3c04d2f
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
