apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-20/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:1716945f42d181821d99165345b0d4ba2a15dea7e13ac962a3128834eee93927
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
