apiVersion: v1
data:
  config.yaml: |
    database.url: postgresql://backend-pr-18/app
kind: ConfigMap
metadata:
  name: backend-9bfbtcfkh4
  namespace: pr-18
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/backend@sha256:3d44dfa57314058fc30aaadd2c54e167a913a0efaac3caf6233f02ecac0e2d8d
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend-9bfbtcfkh4
        name: config
