apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/frontend@sha256:18440f665545bbd29baba86ccf0134115e12bdb591f0db865cbb4a353dfcff37
