apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pr-20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/frontend@sha256:3d16fa92829c5bc5c276ff5be054c9049e1089522c4e694e4eb91c8bf3047881
