apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pr-15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/quipper/monorepo-deploy-actions-demo/frontend@sha256:7437630e5061153540c5697619d94cb3956bc1f3d6bc7364cb7ee10fa59a371e
        volumeMounts:
        - mountPath: /app/config
          name: config
      volumes:
      - configMap:
          name: backend
        name: config
