apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pr-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ${DOCKER_IMAGE}
